__PyTorch__ Demo

In [3]:
import numpy as np 
import torch
import torch.nn as nn   # Neural Network module

import matplotlib.pyplot as plt 
%config InlineBackend.figure_format='svg'

import pprint
pp = pprint.PrettyPrinter()

1. Tensors

In [5]:
lists_of_list = [
    [1, 2, 3],
    [4, 5, 6]
]
lists_of_list

[[1, 2, 3], [4, 5, 6]]

In [7]:
# Initializing a tensor
data = torch.tensor([
    [0, 1],
    [2, 3],
    [4, 5]
    ], dtype=torch.float32)
data

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])

In [9]:
# Utility functions for quick tensor creations
ones_tensor = torch.ones(2, 5)
print(ones_tensor)
zeros_tensor = torch.zeros(3, 4)
print(zeros_tensor)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
