**QP_NET**<br>
by ${\color{orangered}\text{Rishabh Pomaje}}$
- Neural Networks trained to learn how to solve Quadratic Programs

In [1]:
# Dependencies:
import time 
start_time = time.time()
import numpy as np 
import matplotlib.pyplot as plt 
plt.rcParams['font.size'] = 12
%config InlineBackend.figure_format='retina'

import tensorflow as tf 
print(f'{tf.__version__}')

2.16.1


Generating new training data set

<font color='red'>Generating large data set will require a lot of resources and compute time.
It is best to generate the data and store it in .npy format. For every use we can just load the numpy array and be move on.

In [5]:
# To load use this :
def load_training_data(file_path='training_data.npz'):
    """Loads the training data from the specified file."""
    data = np.load(file_path, allow_pickle=True)
    return data['x_train'], data['y_train']

x_train, y_train = load_training_data()

In [7]:
x_train[0]

array([array([[0.25599731, 0.09536265],
              [0.09536265, 0.21936642]]), array([0.21562167, 0.81561645]),
       0.8051088471994223, array([[-0.8904468 , -0.02440685],
                                  [-0.69100325, -0.50744263]]),
       array([-0.56645127,  0.86837312]),
       array([[-0.1214156 ,  0.08606821],
              [ 0.47228723,  0.35708138]]),
       array([-0.90808367,  0.18979562])], dtype=object)

Defining the Neural Network that will learn how to solve _Quadratic Programming_

In [4]:
def buildQPnet(dim_x, num_Ineq, num_Eq):
    input_size = dim_x**2+dim_x+1+num_Ineq*dim_x+num_Ineq+num_Eq*dim_x+num_Eq
    # Read all the matrices
    P = tf.keras.layers.Input(shape=(dim_x, dim_x), name="P")
    G = tf.keras.layers.Input(shape=(num_Ineq, dim_x), name="G")
    A = tf.keras.layers.Input(shape=(num_Eq, dim_x), name="A")

    # Read all the vectors
    q = tf.keras.layers.Input(shape=(dim_x,), name="q")
    r = tf.keras.layers.Input(shape=(1,), name="r")
    h = tf.keras.layers.Input(shape=(num_Ineq,), name="h")
    b = tf.keras.layers.Input(shape=(num_Eq,), name="b")

    # Flatten all the matrices 
    P = tf.keras.layers.Flatten()(P)
    G = tf.keras.layers.Flatten()(G)
    A = tf.keras.layers.Flatten()(A)

    # Combined input layer 
    input_layer = tf.keras.layers.Concatenate()([P, q, r, G, h, A, b])

    # Main network :: Hidden layers
    hidden_layer = tf.keras.layers.Dense(input_size, activation='linear', name="hidden_layer")(input_layer)
    hidden_layer = tf.keras.layers.Dense(8*input_size, activation='relu')(hidden_layer)
    hidden_layer = tf.keras.layers.Dense(16*input_size, activation='relu')(hidden_layer)
    hidden_layer = tf.keras.layers.Dense(16*input_size, activation='relu')(hidden_layer)
    hidden_layer = tf.keras.layers.Dense(16*input_size, activation='relu')(hidden_layer)
    hidden_layer = tf.keras.layers.Dense(8*input_size, activation='relu')(hidden_layer)
    
    # Output layer 
    output_layer = tf.keras.layers.Dense(dim_x+num_Ineq+num_Eq, activation='linear')(hidden_layer)

    # Model package 
    kktNet = tf.keras.Model(inputs=[P, q, r, G, h, A, b], outputs=output_layer)

    return kktNet

Training the Neural Network

Testing the Neural Network

Analysis of the results 

$\downarrow$ Rough Work Starts Here $\downarrow$

In [31]:
a = np.array([1, 2, 3])
b = np.array([[2, 0, 1], [3, 4, 1], [1, 1, 1]])
a.T @ [1, 2, 1]

8